### ISSUE TITLE
Set default variable for source_registry

### ISSUE THREAD

**Issue by day0hero** [CloudCtl/CloudCtl#1]
In collector/vars.yml docker.io is hardcoded as the source registry. To workaround rate limiting by some source_registries this should be set as an overridable variable:

`"{{ source_registry | default('quay.io') }}"`

This will use quay.io by default but could be overridden to any value.

The change would be in collector/vars/images.yml and/or global.yml

**Comment by day0hero** [comment]
Re-opening so its tracked in both codesparta and cloudctl

**Comment by usrbinkat** [comment]
resolved with https://github.com/CloudCtl/CloudCtl/pull/2
